FROM mcr.microsoft.com/dotnet/sdk:3.1 AS build
WORKDIR /DependencyInjectionRepository
RUN ls
RUN dotnet publish DependencyInjectionExampleSolution/DepedencyInjectionUsingMVC/DepedencyInjectionUsingMVC.csproj -c release
FROM mcr.microsoft.com/dotnet/aspnet:3.1 AS final
WORKDIR /app
# RUN useradd -u 8765 non-root && chown -R non-root /tmp
RUN adduser --disabled-password --gecos '' non-root && \
    chown -R non-root /app
USER non-root
EXPOSE 5000
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "DependencyInjectionUsingMVC.dll"]
