  name: CD file
  
  on: 
     workflow_run:
      workflows: 
       - CI
      types:
        - completed
     
  jobs:
    AKS_CD_Deployment:
     if: ${{ github.event.workflow_run.conclusion == 'success' }}
     environment:
        name: Dev
     runs-on: ubuntu-latest
     steps:
          - name: Azure CLI
            run: az login --service-principal -u ${{ secrets.DOCKER_LOGIN }} -p ${{ secrets.DOCKER_PASSWORD }} --tenant 406f6fb2-e087-4d29-9642-817873fddc4c
            
          - name: Docker Login
            run: |
              docker login githubcipractice.azurecr.io -u ${{ secrets.DOCKER_LOGIN }} -p ${{ secrets.DOCKER_PASSWORD }}
              
          - name: aks-set 
            uses: azure/aks-set-context@v3
            with:
             resource-group: 'sharnitha-poc'
             cluster-name: 'pracdemoeks'
      
        # Create K8s secrets to pull images
          - name: Create secret in Kubernetes cluster
            uses: Azure/k8s-create-secret@v1.1
            with:
                container-registry-url: https://githubcipractice.azurecr.io
                container-registry-username: '${{secrets.DOCKER_LOGIN}}'
                container-registry-password:  '${{secrets.DOCKER_PASSWORD}}'
                secret-type: docker-registry
                secret-name: docker-image-pull-secret

          - name: Checkout code
            uses: actions/checkout@v4
             
          - name: Deploy to Kubernetes cluster
            uses: Azure/k8s-deploy@v1
            with:        
                # Path to the manifest files which will be used for deployment.
                manifests: |
                  k8s/deployment.yml
                  k8s/service.yml
                images: '${{secrets.DOCKER_LOGIN}}/githubactions-aks-demo:8766479298'
                imagepullsecrets: docker-image-pull-secret
                action: deploy
 
