name: Full_CI

on:
 workflow_call:
    
jobs:
  Dotnet_Task:
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v3 
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 3.1.x
    - name: Listing Dotnet version
      run: dotnet --version 

  Dotnet_Build:
    runs-on: self-hosted
    needs: Dotnet_Task
    steps:
    - name: Checkout code
      uses: actions/checkout@v3 
    - name: dotnet version
      run: dotnet --version


     
  # Docker_Build:
  #  runs-on: ubuntu-latest
  #  needs: Dotnet_Task
  #  env:
  #   GH_TOKEN: ${{ secrets.ARTIFACT_TOKEN }}
  #  steps:
  #    - name: Checkout code
  #      uses: actions/checkout@v4
  #    - name: Docker build using Dockerfile
  #      run: |
  #        cd DependencyInjectionExampleSolution/DepedencyInjectionUsingMVC/
  #        gh run download ${{ github.run_id }}
  #        docker build -t githubcipractice.azurecr.io/demoenv:${{ github.run_id }} .
