name: pr file
on:
  pull_request:
    branches:
    - feature  
jobs:
        
  ManualSonar:
    if: "github.ref != github.event.pull_request.head.ref"
    runs-on: Ubuntu-latest
    steps:
    
    - name: Checkout code
      uses: actions/checkout@v4  
    - uses: sonarsource/sonarqube-scan-action@master
      env:
        SONAR_TOKEN: "squ_e68703675c202448507701bf069fb2c317bf08ca" 
        SONAR_HOST_URL: "http://20.124.81.89:9000/"
      with:
       args: >
         -Dsonar.projectKey=dotnet
    
        
