name: pr file
on:
  push:
    branches:
    - newprbrancj  
jobs:
        
  ManualSonar:
        runs-on: ubuntu-latest
        steps:
        - name: Remove Previous Dotnet Version
          run : |
            cd /usr/share/dotnet/
            rm -rf *
        - name: Checkout code
          uses: actions/checkout@v3
        - name: Setup .NET Core SDK
          uses: actions/setup-dotnet@v3
          with:
            dotnet-version: 3.1.426
        - name: remove java version
          run: | 
            sudo yum remove java-1.*
            sudo yum update
            sudo yum install java-17-openjdk 
        - name: Listing Dotnet version
          run: |
            dotnet --version
            java --version
        
        - name: SonarScanner tool installed
          run: |
            cd DependencyInjectionExampleSolution/DepedencyInjectionUsingMVC/
            dotnet tool install --global dotnet-sonarscanner
            dotnet sonarscanner begin /k:"Project" /d:sonar.host.url="http://20.55.107.191:9090"  /d:sonar.login="sqp_aebaa19186a06f856bc6cca5d6ea1261ca544700"
            dotnet build  -c release -o app/build
            java --version
            dotnet sonarscanner -v
            dotnet sonarscanner end /d:sonar.login="sqp_aebaa19186a06f856bc6cca5d6ea1261ca544700"
            
  
      
          
