name: pr file
on:
  pull_request:
    branches:
    - master
jobs:       
 Sonar_master:
    runs-on: Ubuntu-latest
    steps:    
    - name: Checkout code
      uses: actions/checkout@v4  
    - name: echo
      run: echo "Hello"
    
